---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: rails-k8s-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: rails-k8s-app
      tier: database
  template:
    metadata:
      name: postgres
      labels:
        app: rails-k8s-app
        tier: database
    spec:
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
      - name: postgres
        image: postgres:9.6-alpine
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "123456"
        - name: POSTGRES_DB
          value: "rails_k8s_prod"
        - name: PGDATA
          value: "/var/lib/postgresql/data"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-pv